export const homePageSchema = {
  name: 'homePage',
  title: 'Homepage',
  type: 'document',
  fields: [
    { name: 'seoTitle', title: 'SEO Title', type: 'string' },
    { name: 'seoDescription', title: 'SEO Description', type: 'text', rows: 3 },
    {
      name: 'hero',
      title: 'Hero',
      type: 'object',
      fields: [
        { name: 'heading', title: 'Heading', type: 'text', rows: 3 },
        { name: 'subheading', title: 'Subheading', type: 'string' },
        { name: 'tagline', title: 'Tagline', type: 'string' },
        { name: 'primaryCtaLabel', title: 'Primary CTA Label', type: 'string' },
        { name: 'primaryCtaHref', title: 'Primary CTA Link', type: 'string' },
        { name: 'secondaryCtaLabel', title: 'Secondary CTA Label', type: 'string' },
        { name: 'secondaryCtaHref', title: 'Secondary CTA Link', type: 'string' },
        { name: 'bookingText', title: 'Booking Text', type: 'text', rows: 2 },
        { name: 'bookingLinkLabel', title: 'Booking Link Label', type: 'string' },
        { name: 'bookingLinkHref', title: 'Booking Link', type: 'string' },
        { name: 'eventBadgeLabel', title: 'Event Badge Label', type: 'string' },
        {
          name: 'backgroundImage',
          title: 'Background Image',
          type: 'image',
          options: { hotspot: true },
        },
      ],
    },
    {
      name: 'about',
      title: 'About Section',
      type: 'object',
      fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'descriptionPrimary', title: 'Primary Description', type: 'text', rows: 3 },
        { name: 'descriptionSecondary', title: 'Secondary Description', type: 'text', rows: 3 },
        { name: 'quote', title: 'Quote', type: 'string' },
        { name: 'ctaLabel', title: 'CTA Label', type: 'string' },
        { name: 'ctaHref', title: 'CTA Link', type: 'string' },
      ],
    },
    {
      name: 'podcast',
      title: 'Podcast Section',
      type: 'object',
      fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'subtitle', title: 'Subtitle', type: 'string' },
        { name: 'description', title: 'Description', type: 'text', rows: 3 },
        { name: 'watchTitle', title: 'Watch Title', type: 'string' },
        { name: 'watchDescription', title: 'Watch Description', type: 'string' },
        { name: 'youtubeUrl', title: 'YouTube URL', type: 'url' },
        { name: 'watchNowLabel', title: 'Watch Label', type: 'string' },
      ],
    },
    {
      name: 'community',
      title: 'Community Section',
      type: 'object',
      fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'description', title: 'Description', type: 'text', rows: 3 },
      ],
    },
    {
      name: 'shop',
      title: 'Shop Section',
      type: 'object',
      fields: [
        { name: 'eyebrow', title: 'Eyebrow', type: 'string' },
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'descriptionPrimary', title: 'Primary Description', type: 'text', rows: 3 },
        { name: 'descriptionSecondary', title: 'Secondary Description', type: 'text', rows: 3 },
        { name: 'primaryCtaLabel', title: 'Primary CTA Label', type: 'string' },
        { name: 'primaryCtaHref', title: 'Primary CTA Link', type: 'string' },
        { name: 'secondaryCtaLabel', title: 'Secondary CTA Label', type: 'string' },
        { name: 'secondaryCtaHref', title: 'Secondary CTA Link', type: 'string' },
      ],
    },
    {
      name: 'newsletter',
      title: 'Newsletter Section',
      type: 'object',
      fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'description', title: 'Description', type: 'string' },
        { name: 'buttonLabel', title: 'Button Label', type: 'string' },
      ],
    },
  ],
};
